#!/bin/bash

# invocation
# findxap [-d <desktop>] [-n] <prog> <prog args>

E_REMOTE=`which enlightenment_remote`
DESKTOP=`$E_REMOTE '{ print $2 }'`
FOLLOW=1

while getopts "d:nc:nh" opt; do
  case $opt in
    c)
        CLASS=$OPTARG
        ;;
    d)
        DESKTOP=$OPTARG
      ;;
    n)
        FOLLOW=""
      ;;
    h)
        HELP=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))

prog=$1
shift

while (( "$#" )); do
    args="$args ""$1"
    shift
done

if [ -z "$prog" -o -n "$HELP" ]; then
    echo "invocation: findxap [-d <desktop>] [-n] -c class <prog> <prog args>"
    exit 1
fi

if [ -z "$CLASS" ]; then
    CLASS=$prog
fi

#echo "sending $prog args $args to desktop=$DESKTOP follow=$FOLLOW"

#######################################################################

function search_windows_by_class() {
    shopt -s nocasematch
    for line in `wmctrl -xlp | awk '{ print $1 ":" $4 }' `; do
        id=$(echo $line | cut -d : -f 1)
        curr=$(echo $line | cut -d : -f 2)
        if [[ $curr =~ $CLASS ]]; then
            enlightenment_remote -window-focus $id
            found=1
        fi
    done

    if [ -n "$found" ]; then
        exit
    fi

}

function search_windows_desktop() {
    for wid in `wmctrl -lp | grep $prog | awk '{ print $1 ":" $3 }' `; do
        pid=$(echo $wid | cut -d : -f 2)
        window=$(echo $wid | cut -d : -f 1)
        mine=$(ps -p $pid -o pid,user | grep $USER)
        if [ -n "$mine" ]; then
            WINDOWS="$WINDOWS $window"
        fi
    done
}

function search_windows_pid() {
#    pids=$(ps -C $prog -o pid,user | grep $USER | awk '{ print $1 }')
    pids=$(ps -C $prog -o pid,user | grep $USER | sed -e 's/^ //' | cut -d \  -f 1)
    if [ -n "$pids" ]; then
        windows_pid=$(wmctrl -lp | grep -E "$pids" | cut -d \  -f 1)
        WINDOWS="$WINDOWS $windows_pid"
    fi
}

function search_windows() {
    search_windows_by_class
    search_windows_desktop
    search_windows_pid
}

function switch_desktop() {
    if [ -e $E_REMOTE ]; then
        $E_REMOTE -desktop-show $DESKTOP 1
    else
        wmctrl -s $DESKTOP
    fi
}

#######################################################################

if [ -n "$FOLLOW" ]; then
    switch_desktop
fi

search_windows
counter=0
while [ -z "$WINDOWS" -a $counter -lt 10 ]; do
    if [ $counter -eq 0 ]; then
        if [ -n "$FOLLOW" ]; then
            wmctrl -s $DESKTOP
        fi
        echo "launching $prog $args"
        $prog $args &
    fi
    let counter=counter+1
    sleep 1
    search_windows
done

for w in $WINDOWS; do
    echo $w
    wmctrl -i -r $w -t $DESKTOP
    if [ -n "$FOLLOW" ]; then
        title=$(wmctrl -l | grep $w | awk '{ out=$4; for(i=5;i<=NF;i++){out=out" "$i}; print out}')
        echo follow $DESKTOP $title
        wmctrl -a "$title"
    fi
done

if [ -n "$FOLLOW" ]; then
    switch_desktop
fi

exit 0
