#!/bin/bash

# invocation
# findxap [-d <desktop>] [-n] <prog> <prog args>


DESKTOP=0
FOLLOW=1

while getopts "d:n" opt; do
  case $opt in
    d)
        DESKTOP=$OPTARG
      ;;
    n)
        FOLLOW=""
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))

prog=$1
shift

while (( "$#" )); do
    args="$args ""$1"
    shift
done

if [ -z "$prog" ]; then
    echo "invocation: findxap [-d <desktop>] [-n] <prog> <prog args>"
    exit 1
fi

#echo "sending $prog args $args to desktop=$DESKTOP follow=$FOLLOW"

#######################################################################

function search_windows_desktop() {
    for wid in `wmctrl -lp | grep $prog | awk '{ print $1 ":" $3 }' `; do
        pid=$(echo $wid | cut -d : -f 2)
        window=$(echo $wid | cut -d : -f 1)
        mine=$(ps -p $pid -o pid,user | grep $USER)
        if [ -n "$mine" ]; then
            WINDOWS="$WINDOWS $window"
        fi
    done
}

function search_windows_pid() {
    pids=$(ps -C $prog -o pid,user | grep $USER | cut -d \  -f 1)
    if [ -n "$pids" ]; then
        windows_pid=$(wmctrl -lp | grep -E "$pids" | cut -d \  -f 1)
        WINDOWS="$WINDOWS $windows_pid"
    fi
}

function search_windows() {
    search_windows_desktop
    search_windows_pid
}

#######################################################################

search_windows
if [ -z "$WINDOWS" ]; then
    echo "launching $prog $args"
    $prog $args &
    sleep 1
    search_windows
fi
#echo "Found $prog at $WINDOWS"

for w in $WINDOWS; do
    wmctrl -i -r $w -t $DESKTOP
    if [ -n "$FOLLOW" ]; then
        wmctrl -a `wmctrl -l | grep $w | cut -d \  -f 5-`
    fi
done

exit 0
