#!/bin/bash

# invocation
# findxap <desktop> <prog> <prog args>

if [ $# -lt 2 ]; then
    echo "invocation: findxap <desktop> <prog> <prog args>"
    exit 1
fi

desk=$1
prog=$2
args=""
shift
shift

while (( "$#" )); do
    args="$args ""$1"
    shift
done

#######################################################################

function search_windows_desktop() {
    for wid in `wmctrl -lp | grep $prog | awk '{ print $1 ":" $3 }' `; do
        echo $wid
        pid=$(echo $wid | cut -d : -f 2)
        window=$(echo $wid | cut -d : -f 1)
        mine=$(ps -p $pid -o pid,user | grep $USER)
        if [ -n "$mine" ]; then
            WINDOWS="$WINDOWS $window"
        fi
    done
}

function search_windows_pid() {
    pids=$(ps -C $prog -o pid,user | grep $USER | cut -d \  -f 1)
    if [ -n "$pids" ]; then
        windows_pid=$(wmctrl -lp | grep -E "$pids" | cut -d \  -f 1)
        WINDOWS="$WINDOWS $windows_pid"
    fi
}

function search_windows() {
    search_windows_desktop
    search_windows_pid
}

#######################################################################

search_windows
if [ -z "$WINDOWS" ]; then
    echo "launching $prog $args"
    $prog $args &
    sleep 1
    search_windows
fi
#echo "Found $prog at $WINDOWS"

for w in $WINDOWS; do
    wmctrl -i -r $w -t $desk
done

wmctrl -s $desk

exit 0
